### ISSUE TITLE
Adafruit Feather ESP32-S3 TFT Support

### ISSUE THREAD

**Issue by beautifully-br0ken** [UnexpectedMaker/esp32s3-arduino-helper#1]
Hello,

When I try to use this library with my Adafruit Feather ESP32-S3 TFT I get the following error, "The board you have selected is not compatible with the UMS3 helper library." Should this board be supported by the library since its a Feather S3?

Thanks!

**Comment by UnexpectedMaker** [comment]
No, my board is `FeatherS3` - That it is actual name. It's a very different board to Adafruit's.
This library is a helper for my ESP32-S3 boards - FeatherS3, TinyS3 and ProS3.
