### ISSUE TITLE
OMGS3 not supported

### ISSUE THREAD

**Issue by dskw** [UnexpectedMaker/esp32s3-arduino-helper#5]
The documentation on help.unexpectedmaker.com points to this library for the OMGS3 to make use of the battery load and LED usage.
But when compiling with arduino the library complains about the board being unsupported.

Can I simply ignore the warning / modify the source, or is it truly incompatible?

```
In file included from [...]\arduino\libraries\UMS3_Helper\examples\LED\LED.ino:1:
[...]\arduino\libraries\UMS3_Helper\src/UMS3.h:20:2: error: #error "The board you have selected is not compatible with the UMS3 helper library"
   20 | #error                                                                         \
      |  ^~~~~
exit status 1
```

**Comment by UnexpectedMaker** [comment]
OMGS3 is not supported in this library right now. You can't just bypass that message.

Where does it state in the help docs it's for OMGS3?

**Comment by dskw** [comment]
Ok my bad again. I need to better pay attention to footnotes..

Got it from here, but overlooked the note at the end that it will be "available soon"
https://help.unexpectedmaker.com/index.php/knowledge-base/where-can-i-find-the-helper-libraries-and-shipping-files-for-my-board/

I'll close the ticket in shame 😆

**Comment by UnexpectedMaker** [comment]
Hahaha - all good. I am working on an updated version that has support for OMGS3 and FeatherS3 Neo, but no ETA right now, sorry.

**Comment by dskw** [comment]
No problem! In the meantime I guess I can simply pull IO34 high and use any neopixel library on pin 35 to use the LED?

I have a lot of time to wait for the fuel gauge support, but being able to make early use of the LED would be neat for designing the housing of my project.

**Comment by UnexpectedMaker** [comment]
Yes, you can just use the Adafruit neopixel library to drive it.
For the fuel gauge. Adafruit also make a comprehensive library for it.
